#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: e:/
#  file: E:/repository/Spring-boot-sell/log/sell.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 8781288aa
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
  jpa:
    show-sql: true

  jackson:
    default-property-inclusion: non_null

  server:
    context-path: /sell
